version: "3"

services:
    back-end:
        build: '.'
        container_name: what-to-watch-tonight_bff
        image: what-to-watch-tonight_bff
        working_dir: /app
        env_file:
        - docker.env
        volumes:
        - ./:/app
        expose:
        - 5000
        ports:
        - 5000:5000
        networks:
        - wtwt

networks:
    wtwt:
        name: wtwt
        driver: bridge
